### PR TITLE
Update to Minecraft 1.20.2 + MP/SP config option

### PR DESCRIPTION
**Pull request by TheMrEngMan**
Add config option to only activate in singleplayer, multiplayer, or both.
Bump version to 1.1.2

Build: https://github.com/TheMrEngMan/totem-indicator/releases/tag/1.1.2

### CODE REVIEW

**Comment by TimeCubed** [comment]
Yet again you make an awesome PR. This time I won't forget to upload it. Thank you very much once again!

**Comment by TimeCubed** [comment]
I do want to ask you though, what do you mean by MP/SP config options?

**Comment by TheMrEngMan** [comment]
MP/SP config options is just the short format name I used in the PR title.
It refers to the same feature: a new button on the configuration screen to select if the totem indicator should be shown only on multiplayer servers, only in singleplayer worlds, or both.

**Comment by TimeCubed** [comment]
> MP/SP config options is just the short format name I used in the PR title. It refers to the same feature: a new button on the configuration screen to select if the totem indicator should be shown only on multiplayer servers, only in singleplayer worlds, or both.

Ah nice. Thank you again for the awesome work.
Also, I would like to ask you about a few more things as I sort out a bunch of things to upload to modrinth. Can we continue this on discord?

**Pull request merged**
